kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 3000 # kind cluster port
        hostPort: 3000 # localhost port
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 5000
        hostPort: 5000
        protocol: tcp
  - role: worker
  - role: worker
  - role: worker
